Feature/add opinion
enterprise-python/event-planner pull request #55
Opened 2018-05-28 10:22 UTC by Shaid3r

Implement #46

2018-05-28 14:00 UTC, fisheye36 commented on website/views.py
> +            raise Http404
`Http404()`

2018-05-28 14:03 UTC, fisheye36 commented on website/templates/website/pages/add_opinion.html
> +{% endblock %}
No newline at the end of the file.

2018-05-28 14:04 UTC, fisheye36 requested changes
Fix commented lines.

2018-05-28 14:48 UTC, ptr97 approved these changes

2018-05-28 21:20 UTC, michaszcz commented on website/templates/website/pages/add_opinion.html
> +{% endblock %}
This is only temporary template to pass view tests.

2018-05-30 15:16 UTC, fisheye36 approved these changes

2018-05-30 15:16 UTC, merged